### PR TITLE
1.2.0 release branch: Remove Ads feature

### PR DESCRIPTION
**Pull request by corycaywood**
# Description
The Ads feature isn't part of the 1.2.0 release scope, so I have removed this feature for the release branch.

# Checklist
- [x] I wrote/updated tests for new/changed code.
- [x] I ran `yarn sdk buildSdk` and `yarn bridge buildBridge` without issues.
- [x] I ran `yarn sample prettify` and `yarn sample build` without issues.

### CODE REVIEW

**Review by Abhijit-majumder — APPROVED** [review]

**Review by ts-leojoseph-r — APPROVED** [review]
Looks good to me :+1:

**Review by Climbatize — APPROVED** [review]
LGTM

**Review by khairul-alam-licon — APPROVED** [review]
👍

**Review by Abhijit-majumder — COMMENTED** [review]
👍

**Pull request merged**
