### PR TITLE
Release preparation for SDK v1.3.0

### PR DESCRIPTION
**Pull request by corycaywood**
# Description
Note: This is being merged into the `release/1.3.0` branch.

- refactor (sdk) Remove screen orientation interface
  - This won't be included in the 1.3.0 release, but will be included in the next release
- docs: (sdk) Update changelog for v1.3.0

## Links
Add links to github/jira issues, design documents and other relevant resources (e.g. previous discussions, platform/tool documentation etc.)

# Checklist
- [x] I wrote/updated tests for new/changed code.
- [x] I ran `yarn sdk buildSdk` and `yarn bridge buildBridge` without issues.
- [x] I ran `yarn sample prettify` and `yarn sample build` without issues.

### CODE REVIEW

**Review by ts-leojoseph-r — APPROVED** [review]
Looks good to me :+1:

**Review by khairul-alam-licon — APPROVED** [review]
👍

**Review by minh-rakuten — COMMENTED** [review]
Need to remove this [part](https://github.com/rakutentech/js-miniapp/blob/c735430dbd9bcccdc4d2f424303dd5a40b5108ba/js-miniapp-sdk/README.md#6-set-screen-orientation) too.

**Comment by corycaywood** [comment]
> Need to remove this [part](https://github.com/rakutentech/js-miniapp/blob/c735430dbd9bcccdc4d2f424303dd5a40b5108ba/js-miniapp-sdk/README.md#6-set-screen-orientation) too.

Oh right, thanks. The most important part 😣

**Review by Abhijit-majumder — APPROVED** [review]
Looks Good! 👍

**Review by minh-rakuten — APPROVED** [review]
👍

**Pull request merged**
