### PR TITLE
[MINI-4413]added hostLocale variable to HostEnvironmentInfo

### PR DESCRIPTION
**Pull request by Climbatize**
# Description
added hostLocale variable to HostEnvironmentInfo

## Links
[MINI-4413]

# Checklist
- [ ] I wrote/updated tests for new/changed code.
- [X] I ran `yarn sdk buildSdk` and `yarn bridge buildBridge` without issues.
- [ ] I ran `yarn sample prettify` and `yarn sample build` without issues.

### CODE REVIEW

**Comment by laubengaier** [comment]
@Climbatize how about adding an option in the settings to change the locale for QA to test with?

**Comment by Climbatize** [comment]
> @Climbatize how about adding an option in the settings to change the locale for QA to test with?

we'll have to do that on iOS/Android side -> We detect the phone is in german, we don't manage this locale, we send en-US or js-JA or anything set in a new setting field on iOS/Android sample app to the MiniApp. The JS sample app has no control on this, it's totally dependent on the host app

**Review by laubengaier — APPROVED** [review]
lgtm

**Review by khairul-alam-licon — APPROVED** [review]
LGTM

**Pull request merged**
