### PR TITLE
Remove webp file

### PR DESCRIPTION
**Pull request by corycaywood**
# Description
Webp files are not currently supported.

# Checklist
- [x] I wrote/updated tests for new/changed code.
- [x] I ran `yarn sdk buildSdk` and `yarn bridge buildBridge` without issues.
- [x] I ran `yarn sample prettify` and `yarn sample build` without issues.

### CODE REVIEW

**Review by khairul-alam-licon — APPROVED** [review]
👍 👍

**Comment by minh-rakuten** [comment]
There is a trick that we still can use WebP by renaming the file 😆. Please see [here](https://github.com/minh-rakuten/js-miniapp/commit/32f3c32d94b0fe7fa5002fa744940b67d57bd02c).

**Comment by corycaywood** [comment]
> There is a trick that we still can use WebP by renaming the file 😆. Please see [here](https://github.com/minh-rakuten/js-miniapp/commit/32f3c32d94b0fe7fa5002fa744940b67d57bd02c).

Oh nice, that works too 😄  Thanks, I've updated this.

**Review by ts-leojoseph-r — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
