### PR TITLE
Sample app updates for QA testability

### PR DESCRIPTION
**Pull request by corycaywood**
# Description
- sample: (ads) Add input fields and 'load' buttons
  - This is needed so all test cases can be covered in QA
- sample: (uri) Add external webview page with tel and _blank links
  - This HTML file is accessed via the raw github url.

# Checklist
- [x] I wrote/updated tests for new/changed code.
- [x] I ran `yarn sdk buildSdk` and `yarn bridge buildBridge` without issues.
- [x] I ran `yarn sample prettify` and `yarn sample build` without issues.

### CODE REVIEW

**Review by khairul-alam-licon — APPROVED** [review]
👍

**Review by minh-rakuten — COMMENTED** [review]
Looks good!

Only one thing about the error display in ad app. It's better to have the two error displays for two types of ad, also we can show the error message from sdk instead of showing the default error message.

**Comment by corycaywood** [comment]
> Looks good!
> 
> Only one thing about the error display in ad app. It's better to have the two error displays for two types of ad, also we can show the error message from sdk instead of showing the default error message.

Thanks, this is a good idea. I have updated with these changes. Also, the JSX portion was getting pretty long (and had some duplicate code) so I refactored a little to have separate render methods.

**Review by minh-rakuten — APPROVED** [review]
👍 👍

**Pull request merged**
